services:
  mysql:
    image: mysql:8.4
    container_name: barbord-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barbord
      MYSQL_USER: barbord
      MYSQL_PASSWORD: barbord
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-uroot', '-proot']
      interval: 60s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: